logging:
  level:
    root: ERROR
    org.libelektra: INFO
#    org.libelektra.KeySet: DEBUG
    org.libelektra.Key: DEBUG
    org.libelektra.errortypes: INFO

mountpoint:
    config: "system/lyrebird"
    specification: "system/spec"
    inject: "system/inject"

injection:
  iterations: 20
#  run-config-location: "/tmp/lcdd-tmp.conf"
  run-config-location: "/home/wespe/.ccm/LyreBirdCluster/node1/conf/cassandra.yaml"
  timeout: 15000
  seed: 19

special.injections: "special-configurations/lcdproc"
outputpath: "/home/wespe/Desktop"

spring:
  profiles:
   active:
#    - lcdproc
    - cassandra
#    - manual
    - all
#    - domain
#    - semantic
#    - typo
#    - structure
#    - resource
#    - limit