logging:
  level:
    root: ERROR
    org.libelektra: INFO
    org.libelektra.errortypes: INFO


randomizer.seed: 19
config.mountpoint: "system/lcdproc"
special.injections: "special-configurations/lcdproc"

injection:
  iterations: 6
  run-config-location: "/tmp/lcdd-tmp.conf"
  timeout: 300

outputpath: "/home/wespe/Desktop"

spring:
  profiles:
   active:
    - lcdproc
    - manual
#    - all
#    - domain
#    - semantic
#    - typo
#    - structure
#    - resource
#    - limit